<?php

namespace HOSparePartBundle\Repository;

/**
 * SparePartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SparePartRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllNotUsed(){
		$qb = $this->createQueryBuilder('s');
		$qb->select('s');
		$qb->where('s.isUsed = false');

		return $qb->getQuery()->getResult();

	}


	public function findAllNotUsedByType($id){
		$qb = $this->createQueryBuilder('s');
		$qb->select('s');
		$qb->innerJoin('s.type', 't', 'WITH', 't.id = :id');
		$qb->where('s.isUsed = false');
		$qb->setParameter('id',$id);

		return $qb->getQuery()->getResult();

	}


	public function findCountAllUsedByType(){
		$qb = $this->createQueryBuilder('s');
		$qb->select('t.name, count(s.id) as counter');
		$qb->innerJoin('s.type', 't');
		$qb->where('s.isUsed = true');
		$qb->groupby('t.name');

		return $qb->getQuery()->getResult();

	}
}
