<?php

namespace HOSparePartBundle\Repository;

/**
 * SparePartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SparePartRepository extends \Doctrine\ORM\EntityRepository
{
}
