<?php

namespace HOSparePartBundle\Repository;

/**
 * SparePartTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SparePartTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
