<?php

namespace HOEquipmentBundle\Repository;

/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{

	public function findEquipments(){
		$qb = $this->createQueryBuilder('e');
		$qb->select('e');
		$qb->where('e.toolBox IS NULL');

		return $qb->getQuery()->getResult();

	}

	public function findEquipmentsCount(){
		$qb = $this->createQueryBuilder('e');
		$qb->select('COUNT(e)');
		$qb->where('e.toolBox IS NULL');

		return $qb->getQuery()->getSingleScalarResult();

	}

	public function findMaterialInterventions(){
		$qb = $this->createQueryBuilder('e');
		$qb->select('e');
		$qb->where('e.toolBox IS NOT NULL');

		return $qb->getQuery()->getResult();
	}

	public function findEquipmentsToControl(){
		$qb = $this->createQueryBuilder('e');
		$qb->select('e');
		$qb->where('e.isBroken = true');

		return $qb->getQuery()->getResult();

	}
}
