<?php

namespace HOEquipmentBundle\Repository;

/**
 * EquipmentStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentStateRepository extends \Doctrine\ORM\EntityRepository
{
}
