<?php

namespace HOEquipmentBundle\Repository;

/**
 * EquipmentCategoryFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentCategoryFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
