<?php

namespace HOEquipmentBundle\Repository;

/**
 * EquipmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
