<?php

namespace HOEquipmentBundle\Repository;

/**
 * EquipmentBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
