<?php

namespace HOEquipmentBundle\Repository;

/**
 * EquipmentReparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentReparationRepository extends \Doctrine\ORM\EntityRepository
{
}
