<?php

namespace HOEquipmentBundle\Repository;

/**
 * PanneTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanneTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
