ho_equipment_homepage:
    path:     /equipment
    defaults: { _controller: HOEquipmentBundle:Equipment:index }

ho_category_homepage:
    path:     /categ
    defaults: { _controller: HOEquipmentBundle:EquipmentCategory:index }



ho_equipment_reparation:
    path:     /eq/reparation/{id}
    defaults: { _controller: HOEquipmentBundle:Equipment:reparationEquipment }

ho_equipment_broken:
    path:     /eq/brok/{id}
    defaults: { _controller: HOEquipmentBundle:Equipment:isBroken }






ho_create_equipment:
    path:     /create/equipment
    defaults: { _controller: HOEquipmentBundle:Equipment:create }

ho_create_category:
    path:     /create/categ
    defaults: { _controller: HOEquipmentBundle:EquipmentCategory:create }





ho_update_equipment:
    path:     /update/equipment/{id}
    defaults: { _controller: HOEquipmentBundle:Equipment:update }

ho_update_category:
    path:     /update/categ/{id}
    defaults: { _controller: HOEquipmentBundle:EquipmentCategory:update }







ho_delete_equipment:
    path:     /del/equipment/{id}
    defaults: { _controller: HOEquipmentBundle:Equipment:delete }

ho_delete_category:
    path:     /del/categ/{id}
    defaults: { _controller: HOEquipmentBundle:EquipmentCategory:delete }







