ho_stock_homepage:
    path:     /stock 
    defaults: { _controller: HOStockBundle:Default:index }


ho_create_stock:
    path:     /create/stock
    defaults: { _controller: HOStockBundle:Default:create }

ho_update_stock:
    path:     /update/stock/{id}
    defaults: { _controller: HOStockBundle:Default:update }

ho_delete_stock:
    path:     /del/stock/{id}
    defaults: { _controller: HOStockBundle:Default:delete }


ho_stock_add_spare_part:
    path:    /stock/add/spar/{stockId}
    defaults: { _controller: HOStockBundle:Default:addSparePart }
