ho_company:
    resource: "@HOCompanyBundle/Resources/config/routing.yml"
    prefix:   /


ho_spare_part:
    resource: "@HOSparePartBundle/Resources/config/routing.yml"
    prefix:   /

ho_equipment:
    resource: "@HOEquipmentBundle/Resources/config/routing.yml"
    prefix:   /

ho_user:
    resource: "@HOUserBundle/Controller/"
    type:     annotation
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile 


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
