# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        HOUserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER, ROLE_MODERATOR, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
                default_target_path: /
            logout: 
                path:       fos_user_security_logout
                target: /
            remember_me:
                key: %secret%

    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/gest, roles: ROLE_MODERATOR }
        
