ho_moderator_homepage:
    path:     /admin/mod/
    defaults: { _controller: HOCompanyBundle:Default:index }

ho_create_moderator:
    path:     /admin/add/mod/
    defaults: { _controller: HOCompanyBundle:Default:addModerator }


ho_disable_moderator:
    path:     /admin/mod/dis/{id}
    defaults: { _controller: HOCompanyBundle:Default:disableModerator }

ho_enable_moderator:
    path:     admin/mod/ena/{id}
    defaults: { _controller: HOCompanyBundle:Default:enableModerator }


ho_delete_moderator:
    path:     /admin/mod/del/{id}
    defaults: { _controller: HOCompanyBundle:Default:deleteModerator }









ho_repairer_homepage:
    path:     /gest/repairer
    defaults: { _controller: HOCompanyBundle:Repairer:index }



ho_service_homepage:
    path:    /serv
    defaults: { _controller: HOCompanyBundle:Service:index }

ho_abscence_homepage:
    path:     /gest/abs/
    defaults: { _controller: HOCompanyBundle:Repairer:abscencesList }







ho_create_repairer:
    path:     /gest/create/repairer
    defaults: { _controller: HOCompanyBundle:Repairer:create }

ho_create_repairer_abscence:
    path:     /gest/create/rep/abs/
    defaults: { _controller: HOCompanyBundle:Repairer:createAbscence }



ho_create_service:
    path:    /gest/create/serv
    defaults: { _controller: HOCompanyBundle:Service:create }






ho_update_repairer:
    path:     /gest/update/repairer/{id}
    defaults: { _controller: HOCompanyBundle:Repairer:update }



ho_update_service:
    path:    /gest/update/serv/{id}
    defaults: { _controller: HOCompanyBundle:Service:update }







ho_delete_repairer:
    path:     /admin/del/repairer/{id}
    defaults: { _controller: HOCompanyBundle:Repairer:delete }



ho_delete_service:
    path:    /admin/del/serv/{id}
    defaults: { _controller: HOCompanyBundle:Service:delete }


ho_delete_abscence:
    path:     /admin/del/abs/{id}
    defaults: { _controller: HOCompanyBundle:Repairer:deleteAbscence }



ho_service_add_room:
    path:    /gest/serv/{serviceId}/add_room
    defaults: { _controller: HOCompanyBundle:Service:addRoom }




ho_repairer_interventions:
    path:     /gest/repairer/interventions/{id}
    defaults: { _controller: HOCompanyBundle:Repairer:repairerInterventions }

ho_repairer_abscences:
    path:     /gest/repairer/{id}/abscences
    defaults: { _controller: HOCompanyBundle:Repairer:repairerAbscences }


ho_repairers_compare_by_year:
    path:     /gest/repairers/comp/year
    defaults: { _controller: HOCompanyBundle:Repairer:compareByYear }

ho_repairers_compare_by_month:
    path:     /gest/repairers/comp/month
    defaults: { _controller: HOCompanyBundle:Repairer:compareByMonth }

ho_service_equipments:
    path:     /gest/serv/{id}/eqs
    defaults: { _controller: HOCompanyBundle:Service:equipmentsService }













