ho_moderator_homepage:
    path:     /mod/
    defaults: { _controller: HOCompanyBundle:Default:index }

ho_create_moderator:
    path:     /add/mod/
    defaults: { _controller: HOCompanyBundle:Default:addModerator }


ho_disable_moderator:
    path:     /mod/dis/{id}
    defaults: { _controller: HOCompanyBundle:Default:disableModerator }

ho_enable_moderator:
    path:     /mod/ena/{id}
    defaults: { _controller: HOCompanyBundle:Default:enableModerator }


ho_delete_moderator:
    path:     /mod/del/{id}
    defaults: { _controller: HOCompanyBundle:Default:deleteModerator }









ho_repairer_homepage:
    path:     /repairer
    defaults: { _controller: HOCompanyBundle:Repairer:index }


ho_zone_homepage:
    path:     /zone
    defaults: { _controller: HOCompanyBundle:Zone:index }

ho_service_homepage:
    path:    /serv
    defaults: { _controller: HOCompanyBundle:Service:index }







ho_create_repairer:
    path:     /create/repairer
    defaults: { _controller: HOCompanyBundle:Repairer:create }



ho_create_zone:
    path:     /create/zone
    defaults: { _controller: HOCompanyBundle:Zone:create }

ho_create_service:
    path:    /create/serv
    defaults: { _controller: HOCompanyBundle:Service:create }






ho_update_repairer:
    path:     /update/repairer/{id}
    defaults: { _controller: HOCompanyBundle:Repairer:update }



ho_update_zone:
    path:     /update/zone/{id}
    defaults: { _controller: HOCompanyBundle:Zone:update }

ho_update_service:
    path:    /update/serv/{id}
    defaults: { _controller: HOCompanyBundle:Service:update }







ho_delete_repairer:
    path:     /del/repairer/{id}
    defaults: { _controller: HOCompanyBundle:Repairer:delete }



ho_delete_zone:
    path:     /del/zone/{id}
    defaults: { _controller: HOCompanyBundle:Zone:delete }

ho_delete_service:
    path:    /del/serv/{id}
    defaults: { _controller: HOCompanyBundle:Service:delete }




ho_service_add_room:
    path:    /serv/{serviceId}/add_room
    defaults: { _controller: HOCompanyBundle:Service:addRoom }


ho_service_add_equipment_base:
    path:    /servbase/add/eq/{serviceId}
    defaults: { _controller: HOCompanyBundle:Service:addEquipmentBase }

ho_service_add_equipment_stock:
    path:    /servstock/add/eq/{serviceId}
    defaults: { _controller: HOCompanyBundle:Service:addEquipmentFromStock }


ho_repairer_interventions:
    path:     /repairer/interventions/{id}
    defaults: { _controller: HOCompanyBundle:Repairer:repairerInterventions }












