<?php

namespace HOCompanyBundle\Repository;

/**
 * AlertServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
