<?php

namespace HOCompanyBundle\Repository;

/**
 * ServiceRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
