<?php

namespace HOInterventionBundle\Repository;

/**
 * AlertStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertStateRepository extends \Doctrine\ORM\EntityRepository
{
}
