<?php

namespace HOInterventionBundle\Repository;

/**
 * AlertCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
