<?php

namespace HOInterventionBundle\Repository;

/**
 * AlertServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertServiceRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllFromService($serviceId){
		$qb = $this->createQueryBuilder('a');
		$qb->select('a');
		$qb->innerJoin('a.service', 's', 'WITH', 's.id = :service');
		$qb->setParameter('service',$serviceId);

		return $qb->getQuery()->getResult();
	}
}
