<?php

namespace HOInterventionBundle\Repository;

/**
 * InterventionEquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionEquipmentRepository extends \Doctrine\ORM\EntityRepository
{

	public function findLastIntervention($equipmentId){
		$qb = $this->createQueryBuilder('i');
		$qb->select('i');
		$qb->where('i.equipment = :equipment');
		$qb->andWhere('i.isBack = false ');
		$qb->setParameter('equipment',$equipmentId);

		return $qb->getQuery()->getOneOrNullResult();

	}

}
