<?php

namespace HOInterventionBundle\Repository;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllCurrent(){
		$qb = $this->createQueryBuilder('i');
		$qb->select('i');
		$qb->where('i.isClosed = false ');

		return $qb->getQuery()->getResult();

	}

	
}
