<?php

namespace HOInterventionBundle\Repository;

/**
 * InterventionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
