<?php

namespace HOInterventionBundle\Repository;

/**
 * ToolBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolBoxRepository extends \Doctrine\ORM\EntityRepository
{
}
